### ISSUE TITLE
Publish artifacts to Maven Central

### ISSUE THREAD

**Issue by heuermh** [awslabs/aws-java-nio-spi-for-s3#1]
A request to publish the artifacts from this project to Maven Central.

**Comment by sigpwned** [comment]
Any luck publishing to Maven Central? This is very useful code, and it would be really nice to have it easily available for third-party builds! I'll happily volunteer time to help, if that's in any way useful.

**Comment by markjschreiber** [comment]
Apologies for the slow progress on this one. A number of other things came up. Currently working through getting signing keys and sonatype access.

@sigpwned Thanks for the PR, I will need to change some parts but otherwise it will help.

**Comment by sigpwned** [comment]
No worries, I know we all understand "busy." I expect you will have to change some things, but I'm glad it's at least helpful!

**Comment by markjschreiber** [comment]
Packages are visible at https://repo1.maven.org/maven2/software/amazon/nio/s3/aws-java-nio-spi-for-s3/

**Comment by sigpwned** [comment]
Hot damn! Confirm I can see the packages at https://search.maven.org/search?q=aws-java-nio-spi-for-s3. Thank you, @markjschreiber!

**Comment by heuermh** [comment]
Thank you, @markjschreiber!

Works for me, see commit https://github.com/heuermh/dishevelled-bio/commit/1f976806c691247a5734c35467352b5ca741c386
