### ISSUE TITLE
Update THIRD-PARTY with Junit 5 and AssertJ

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#104]
I think a left over from the merges

** Junit 5.x -- https://junit.org/junit5/
** AssertJ 3.x -- https://assertj.github.io/
** Logback Classic 1.2.x -- https://logback.qos.ch/ -- Copyright © 2021 QOS.ch
** Logback Core 1.2.x -- https://logback.qos.ch/ -- Copyright © 2021 QOS.ch
** System Lambda 1.2.x -- https://github.com/stefanbirkner/system-lambda -- Copyright © 2017 Stefan Birkner

**Comment by markjschreiber** [comment]
Should drop a PR for this today.
