### ISSUE TITLE
Exclude implicit dependencies on HTTP clients?

### ISSUE THREAD

**Issue by sigpwned** [awslabs/aws-java-nio-spi-for-s3#109]
By default, the `software.amazon.awssdk:s3` dependency pulls in both `software.amazon.awssdk:apache-client` and `software.amazon.awssdk:netty-nio-client`. Based on an (admittedly quick) browse of the code, it looks like this project uses the CRT client for async, and doesn't particularly care about which client to use for synchronous usage.

Does it make sense to do either of the following?

1. Add exclusions for `software.amazon.awssdk:apache-client` and `software.amazon.awssdk:netty-nio-client` (both of which are simply large at best, and create version contention at worst), and add an import and code for `software.amazon.awssdk:url-connection-client` (which is tiny, only 32K) for synchronous usage.
2. Add tests to confirm that `software.amazon.awssdk:apache-client` and `software.amazon.awssdk:netty-nio-client` are not needed; add instructions in the docs to inform users that it is safe to exclude `software.amazon.awssdk:apache-client` and `software.amazon.awssdk:netty-nio-client` if they desire, and how to do so; and add instructions in the docs to use `software.amazon.awssdk:url-connection-client` for synchronous requests, and how to do so.

I'm happy to take a swing at either of the above if they make sense.

**Comment by markjschreiber** [comment]
Apologies for not seeing this sooner. I think it is a reasonable suggestion.

**Comment by markjschreiber** [comment]
@sigpwned 
> I'm happy to take a swing at either of the above if they make sense.

I'm wondering if you (or someone else) is still interested in trying this out?
