### ISSUE TITLE
Easy configuration to use in FileSystem.newFileSystem()

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#112]
AS A user
I WANT to be able to provide configuration setting when creating a new file system. E.g.:
```

FileSystems.newFileSystem(myuri, Map.of(
    AWS_ACCESS_KEY_PROPERTY, "access-key",
    AWS_SECRET_ACCESS_KEY_PROPERTY, "secret-key",
    S3_SPI_ENDPOINT_PROTOCOL_PROPERTY, "http"
));
```

SO THAT I can easily provide configuration settings to the file system provider

**NOTES**

1. Use S3NioSpiConfigurationBuilder. E.g. :

```
FileSystems.newFileSystem(myuri, new S3NioSpiConfigurationBuilder()
    .withAccessKey("access-key")
    .withSecretKey("secret-key")
    .withEndpointProtocol("http")
);
```

2. for configuration parameter s3.spi.endpoint  no env var/sys prop overriding because not a good pattern with FileSystems where multiple instances of a file system can be created and are supposed to have their own env, while envvars and sysprops are global to the JVM.

**Comment by markjschreiber** [comment]
Is it OK to close this? I think the mentioned PR includes this.
