### ISSUE TITLE
Switch to Java 11/19

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#113]
This issue is to discuss what we need to do to switch to a modern JDK. I understand there are some limitations maybe due to GitHub actions, is that the case? If so, how can we work around it?

**Comment by markjschreiber** [comment]
The only reason why we shouldn't is that ideally we need to be able to build JDK 1.8 compatible byte code. The main goal of this library is to build a JAR that you can drop in as an SPI provider that can be used with any existing Java application without having to recompile it. Tragically, there are still many existing JDK 1.8 java applications. It would be nice to support them if possible.
