### ISSUE TITLE
Make internals private?

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#129]
https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/20c8e9c0647890a0cdaf6a362fb357aacb2b9e58/src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java#L326

Given that when we have a protected member we want to pay extra attention to the stability of the interface, which makes the codebase more difficult to refactor, would it make sense to make this private?

**Comment by markjschreiber** [comment]
I think it is protected because of a limitation of unit testing that cannot test private methods. It could probably be hidden with a refactoring of the unit test?

**Comment by markjschreiber** [comment]
Using reflection would be an alternative way to test a private method. If it must be tested.

**Comment by stefanofornari** [comment]
Yep, despite I agree that testability justifies not optimal design choices, either we are more flexible in compatibility breaking changes or more careful in using it. 
Either ways work for me. would you take care of it?

**Comment by stefanofornari** [comment]
merged into main with PR #133
