### ISSUE TITLE
createDirectory() with empty path ("")

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#134]
in S3FileSystemProvider.createDirecotry()

https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/e831e674425fd62d48ed4464299d5461e1badad3/src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java#L343-L346

we may throw an exception if Path.getKey() returns an empty (the root) string.

**Comment by markjschreiber** [comment]
Agree, we should also throw an exception if the input `Path` is null

**Comment by markjschreiber** [comment]
Fixed in main
