### ISSUE TITLE
lower the level of logged messages

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#176]
The following should be logged at lower level than info.

https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/17f58a408dd188cee241514856b03c3c15a5b9b5/src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java#L103

https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/17f58a408dd188cee241514856b03c3c15a5b9b5/src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java#L108

https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/17f58a408dd188cee241514856b03c3c15a5b9b5/src/main/java/software/amazon/nio/spi/s3/S3DirectReadableByteChannel.java#L76

https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/17f58a408dd188cee241514856b03c3c15a5b9b5/src/main/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannel.java#L77

**Comment by markjschreiber** [comment]
Agree, these should be debug.
