### ISSUE TITLE
S3SeekableByteChannel ignores local configuration overrides

### ISSUE THREAD

**Issue by lpartington** [awslabs/aws-java-nio-spi-for-s3#191]
S3ReadAheadByteChannel seems to ignore the max fragment size that was set when S3FileSystemProvider.newFileSystem() is called. In the following snippet:

```
S3FileSystemProvider fsp = new S3FileSystemProvider();

Map<String, String> env = new HashMap();
env.put("s3.spi.read.max-fragment-size", "100000");
S3FileSystem fs = fsp.newFileSystem(URI.create(pathUri), env);

Set<StandardOpenOption> opts = new HashSet<StandardOpenOption>();
opts.add(StandardOpenOption.READ);

S3Path s3Path = fs.getPath("s3://mybucket/mybigfile");
S3SeekableByteChannel chan = fsp.newByteChannel(s3Path, opts);
```
the S3ReadAheadByteChannel used by the S3SeekableByteChannel should use a fragment size of 100000 bytes. However, assuming no environment or system property overrides have been set, it continues to use the default fragment size of 5242880 bytes.

The reason this happens is because the S3SeekableByteChannel ctor uses a default-constructed S3NioSpiConfiguration rather than the config in the S3FileSystem:

```
S3NioSpiConfiguration config = new S3NioSpiConfiguration();
readDelegate = new S3ReadAheadByteChannel(s3Path, config.getMaxFragmentSize(), config.getMaxFragmentNumber(), s3Client, this, timeout, timeUnit);
```

The default S3NioSpiConfiguration ctor will use the default property values, or the env var overrides if set, or the system prop overrides if set, but doesn't have any local overrides. The S3SeekableByteChannel should instead do something like:
```
S3NioSpiConfiguration config = s3Path.getFileSystem().configuration();
```

**Comment by markjschreiber** [comment]
The solution you propose seems feasible. It may take me a few days (or possibly a few weeks) to get to this. Feel free to post a PR.
