### ISSUE TITLE
S3WritableByteChannel does not consider contentType while putting an object into the bucket

### ISSUE THREAD

**Issue by aliabdikk** [awslabs/aws-java-nio-spi-for-s3#194]
Upon uploading a file to the bucket, we are not defining any content type:

https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/5e821745263c57d7c00df397a8ce425d3a01a446/src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java#L102-L128

This could be crucial, like when we are uploading a special file (like XML file) to be used by another application later.

I believe something like `.contentType(Files.probeContentType(tempFile))` before building the `putObjectRequest` should do the trick.

**Comment by markjschreiber** [comment]
This is a good suggestion. Looking at the JDK docs I can see that `Files.probeContentType(tempFile)` will return `null` if the contentType cannot be guessed so we will need to check that the `putObjectRequest` will be OK with the value of `.contentType()` being null.

It may take me a couple of weeks to get to this, but feel free to make a PR if you want to see this added faster.

**Comment by aliabdikk** [comment]
@markjschreiber Done:
https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/204

**Comment by markjschreiber** [comment]
PR Merged
