### ISSUE TITLE
Implement `FileSystem.newFileSystem(URI uri, Map<String, ?> env)` to create an S3 bucket

### ISSUE THREAD

**Issue by guicamest** [awslabs/aws-java-nio-spi-for-s3#243]
As requested in https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/227#discussion_r1376469184 and detailed in https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/227#issuecomment-1781937573:

The map (`env`) of key value pairs passed to it would need to map to properties that can be set on the `CreateBucketRequest` operation of the S3Client
The `uri` would need to have a `bucket` (i.e. _s3://my-new-bucket_)

## Available parameters for `CreateBucketRequest`
![image](https://github.com/awslabs/aws-java-nio-spi-for-s3/assets/283778/cdd88203-3dbb-4286-896a-0e616df503de)

## DISCLAIMER
Not to be mistaken with `newFileSystem(Path path, Map<String,?> env)`, which is intended to _Construct a new FileSystem to access the contents _**of a file**_ as a file system_ (Usually for archives like `zip`, does not apply for S3)

**Comment by markjschreiber** [comment]
Implemented in #406
