### ISSUE TITLE
Missing S3FileSystemInfoTest.java

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#284]
Hello, I noticed that the test class in the subject is not anymore there. Is it wanted?

**Comment by markjschreiber** [comment]
Hmm, it may have gone missing during the refactoring. Will need to pull it back in from a prior commit.

**Comment by markjschreiber** [comment]
Just checked back through the last five releases and I'm not sure we ever had a test for this. Unless I am looking in the wrong place. I can see one for `S3XFileSystemInfoTest.java`
