### ISSUE TITLE
S3Path: surprising behavior of the normalize method - turns a path from absolute to relative

### ISSUE THREAD

**Issue by thsandu** [awslabs/aws-java-nio-spi-for-s3#292]
I noticed that normalizing an absolute S3Path results in the path not being absolute anymore. Is this a conscious deviation from other implementations?

Here a small test showing the behavior for Windows and Jimfs:
```
@Test
public void normalizedAbsolute() {
	assertTrue(Paths.get("C:\\foo\\.\\bar").normalize().isAbsolute());
	assertFalse(Paths.get("foo\\.\\bar").normalize().isAbsolute());

	FileSystem linux = Jimfs.newFileSystem("testme", Configuration.unix());
	assertTrue(linux.getPath("/foo/./bar").normalize().isAbsolute());
	assertFalse(linux.getPath("foo/./bar").normalize().isAbsolute());
}
```  

I added here a unit test in my fork to show the issue: https://github.com/thsandu/aws-java-nio-spi-for-s3-issues-with-s3x/blob/378feb0251bc0010bbc9112a9c3c7d6c2166508d/src/test/java/software/amazon/nio/spi/s3/S3PathTest.java#L280

**Comment by markjschreiber** [comment]
This might be fixed with PR #293 ?
