### ISSUE TITLE
Add checkstyle plugin for Gradle

### ISSUE THREAD

**Issue by markjschreiber** [awslabs/aws-java-nio-spi-for-s3#300]
https://docs.gradle.org/current/userguide/checkstyle_plugin.html

**Comment by guicamest** [comment]
Any particular style to follow? Some that come to mind:

* [Google Style Guide definition](https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml)
* [Google Style Guide document](https://google.github.io/styleguide/javaguide.html)
* [Checkstyle for AWS SDK V2](https://github.com/aws/aws-sdk-java-v2/blob/master/build-tools/src/main/resources/software/amazon/awssdk/checkstyle.xml)

**Comment by markjschreiber** [comment]
For consistency I guess I should be recommending Checkstyle for AWS SDK V2 :)
