### ISSUE TITLE
Feature Request: Support Files.move(...)

### ISSUE THREAD

**Issue by Nyamiou** [awslabs/aws-java-nio-spi-for-s3#339]
When doing `Files.move(...)`, Java will go through `CopyMoveHelper.moveToForeignTarget(...)` which has a private method `convertMoveToCopyOptions(...)` which will always add `StandardCopyOption.COPY_ATTRIBUTES` then in the other private method `copyToForeignTarget(...)` it will lead it to go through the `if (opts.copyAttributes)` path and ultimately call the `view.setTimes(...)` method which unfortunately in this library contains:

```
    /**
     * Unsupported operation, write operations are not supported.
     */
    @Override
    public void setTimes(FileTime lastModifiedTime, FileTime lastAccessTime, FileTime createTime) {
        throw new UnsupportedOperationException(
            "write operations are not supported, please submitted a feature request explaining your use case");
    }
 ```

I can workaround it for now by doing a `Files.copy(...)` and then `Files.delete(...)` since the time attributes are not critical. But I would appreciate if you could consider it for future releases.

Thank you.

**Comment by markjschreiber** [comment]
Apologies for the delay in responding.

Objects in S3 only have a created time and to change that the object would have to be recreated (basically copied deleted and rewritten) so `setTimes` isn't really something that can be implemented in any meaningful way. What we could do, to support `Files.move()` is to remove the code that throws the exception and do nothing instead (no-op) other than logging a warning. We would also want to document that this method call is a no-op.

Simple enough for me (or anyone) to implement, do you see any problems with not being able to actually set the times?

**Comment by Nyamiou** [comment]
I wasn't aware of this limitation on S3. In that case, I think your proposed solution is great. Thank you.

**Comment by markjschreiber** [comment]
PR is merged. I believe it resolves the issue. Let me know if it doesn't.
