### ISSUE TITLE
AWS_REGION is ignored => region is locked to us-east-1

### ISSUE THREAD

**Issue by bbilger** [awslabs/aws-java-nio-spi-for-s3#353]
It's currently not possible to change the region e.g. via AWS_REGION or whatever the provider chain would consider.
The problem is that `Region.US_EAST` is set on the builder when none is provided; and none can be provided currently in anyway. Thus it is locked to that region.
https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/935a548f8899b35b25b3377c761d536a34477156/src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java#L300

This problem happens primarily for 3rd party providers but it can also happen for AWS buckets when the region cannot be determined.
https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/935a548f8899b35b25b3377c761d536a34477156/src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java#L170

**Comment by markjschreiber** [comment]
Can you check if this is resolved by PR #400 ?

**Comment by markjschreiber** [comment]
Closing as PR 400 removes the defaulting to region `us-east-1`.

**Comment by bbilger** [comment]
> Can you check if this is resolved by PR #400 ?

Looks good, thanks - sorry for the delay.
