### ISSUE TITLE
Missing version 2.x?

### ISSUE THREAD

**Issue by bulebuk** [awslabs/aws-java-nio-spi-for-s3#392]
README suggests using 2.x.x version for Java 11 and newer. There are no releases, tags, etc for this version. 

Is is still required to use the 2.x.x. version for Java 11 and newer?

**Comment by markjschreiber** [comment]
I do need to publish a 2.0 artifact (or at least a 2.0 release candidate). 

However, you can use earlier releases with any Java version from 8 or higher. We just restricted development of the code to JDK1.8 so that people still restricted to Java 8 would be able to use the code.
