### ISSUE TITLE
Files#createDirectories(Path) causes following operations to fail

### ISSUE THREAD

**Issue by stuartfehr** [awslabs/aws-java-nio-spi-for-s3#435]
We have some code which writes a file using Files#write(Path, byte[]) When the destination file system is the local one, it will fail if the parent directories of the output path do not already exist. So, we call Files#createDirectories(Path) before calling write to ensure that they have been created.

However, when the output file system is S3, the call to write fails with this exception:

> Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: S3Client.makeMetaRequest has invalid client. The client can not be used after it is closed.
> 	at app//software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
> 	at app//software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:223)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:218)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:182)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159)
> 	at java.base@17.0.7/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
> 	at java.base@17.0.7/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source)
> 	at java.base@17.0.7/java.util.concurrent.CompletableFuture.whenComplete(Unknown Source)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.attemptExecute(AsyncRetryableStage.java:156)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:136)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.execute(AsyncRetryableStage.java:95)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:79)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage.execute(AsyncRetryableStage.java:44)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at app//software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.execute(AsyncExecutionFailureExceptionReportingStage.java:41)
> 	... 81 more
> Caused by: java.lang.IllegalStateException: S3Client.makeMetaRequest has invalid client. The client can not be used after it is closed.
> 	at software.amazon.awssdk.crt.s3.S3Client.makeMetaRequest(S3Client.java:129)
> 	at software.amazon.awssdk.services.s3.internal.crt.S3CrtAsyncHttpClient.execute(S3CrtAsyncHttpClient.java:163)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.doExecuteHttpRequest(MakeAsyncHttpRequestStage.java:204)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.executeHttpRequest(MakeAsyncHttpRequestStage.java:151)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$execute$1(MakeAsyncHttpRequestStage.java:104)
> 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(Unknown Source)
> 	at java.base/java.util.concurrent.CompletableFuture.thenAccept(Unknown Source)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:100)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.execute(MakeAsyncHttpRequestStage.java:65)
> 	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallAttemptMetricCollectionStage.execute(AsyncApiCallAttemptMetricCollectionStage.java:62)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallAttemptMetricCollectionStage.execute(AsyncApiCallAttemptMetricCollectionStage.java:41)
> 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.attemptExecute(AsyncRetryableStage.java:144)
> 	... 88 more

If I comment out the call to Files#createDirectories(Path) it works correctly without issue. This leads me to believe that the implementation of createDirectories is doing something to the S3Client that it shouldn't (closing it perhaps?).

**Comment by markjschreiber** [comment]
Hi @stuartfehr, it does seem like Files#createDirectories(Path) is making a sequence of calls one of which is closing the client before the full operation is complete.

Can you add which version of the library you are using?

**Comment by stuartfehr** [comment]
It looks like we were
using software.amazon.nio.s3:aws-java-nio-spi-for-s3:2.0.0 at the time that
I reported this issue. Thanks.

**Comment by markjschreiber** [comment]
Can you share some example code. I just ran this simple program and it appears to work without an issue. This was using `main` although 2.0.1 should also be equivalent.

```
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;

public class CreatePrefix {
    public static void main(String[] args) throws IOException, URISyntaxException {
        var bucketName =  args[0];
        var prefix = args[1];

        if (!prefix.endsWith("/")) {
            prefix += "/";
        }

        var pathUri = Path.of(new URI("s3://" + bucketName + "/" + prefix));

        var pathCreated = Files.createDirectories(pathUri);
        System.out.println("Created:" + pathCreated);
    }
}
```

**Comment by markjschreiber** [comment]
This seems to replicate the error. I will investigate.

```

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;

public class CreatePrefix {
    public static void main(String[] args) throws IOException, URISyntaxException {
        var bucketName =  args[0];
        var prefix = args[1];

        var pathUri = Path.of(new URI("s3://" + bucketName + "/" + prefix));

        var pathCreated = Files.createDirectories(pathUri);
        Files.write(pathCreated, "test-data".getBytes());

        System.out.println("Created:" + pathCreated);
    }
}
```

**Comment by markjschreiber** [comment]
I have made some commits in main that should fix this.

**Comment by stuartfehr** [comment]
Thank you!

**Comment by chbriem** [comment]
@markjschreiber 
AFAICT, this is not fixed in the recent version `2.0.2`. Also your replication example fails on my machine.

Could you have another look into this?

**Comment by markjschreiber** [comment]
Thanks. There was an issue in the cache logic. I have pushed a commit to main. Let me know if you still have issues with it.

**Comment by sberss** [comment]
Thanks for the fix! 

Any chance for an expedited release on this? I was hoping to get this fix in `2.0.2`.

**Comment by markjschreiber** [comment]
I can make a 2.0.3 release?

**Comment by markjschreiber** [comment]
A new release with this fix is here https://github.com/awslabs/aws-java-nio-spi-for-s3/releases/tag/2.0.3

It has been sent Maven Central but usually takes a few hours to show up.
