### ISSUE TITLE
S3WritableByteChannel tries another upload on second close() call

### ISSUE THREAD

**Issue by chbriem** [awslabs/aws-java-nio-spi-for-s3#453]
When using the library (version 2.0.1), we experienced `FileNotFoundExceptions` when writing data.

When further investigating, we found out that the `S3WritableByteChannel.close()` method does not behave as specified: On a second call to an already closed channel, the implementation tries to upload the temp file again, which has been deleted at this time already, of course.

IMHO, this is a violation of the contract of the `Channel.close()` method.

I'm prepared to deliver a fix if desired.

Environment:
 * Windows
 * Java Temurin 21
 * Library version 2.0.1

**Comment by markjschreiber** [comment]
closed by #454
