### ISSUE TITLE
Copy a file from a bucket to another with different credentials

### ISSUE THREAD

**Issue by mirkoscotti** [awslabs/aws-java-nio-spi-for-s3#534]
I need to copy files from my bucket to a bucket managed by an external owner. source and target bucket can be accessed with different credentials. I did not find a way to do this. 

It seems that the library allows copying only when source and target buckets are accessible with the same credentials. Can you confirm this, and in this case I would ask you a new feature to cover my requirement, or show me a way within the current version?
Thx.

**Comment by mirkoscotti** [comment]
Yes, I do not like the use of the intermediate file system... Ok, I will follow your hint. Thx very much.

**Comment by markjschreiber** [comment]
This is a fair point. If you are using an AWS S3 bucket with IAM credentials then you can't do it (other than getting an IAM role with access to both buckets). If you are using something like minio or another S3 like system you could do it as @stefanofornari shows.
