### ISSUE TITLE
Rely concurrently on multiple S3FileSystem in different regions

### ISSUE THREAD

**Issue by blacelle** [awslabs/aws-java-nio-spi-for-s3#554]
I use this as a library. I understand the only way to setup the AWS region is through `System.setProperty("aws.region", Region.US_EAST_1.id());`

Is there a way to configure it out of through a static variables?

More specifically, I need to use concurrently multiple `S3FileSystem`, for different buckets in different AWS regions. Though, the region seems to be nedded not only in `S3FileSystem` setup, but on any later operation:

```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@55044b34: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@406ad6d5: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@5486ee92: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@78128dd0: Unable to contact EC2 metadata service.]
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111) ~[sdk-core-2.28.18.jar:na]
	at software.amazon.awssdk.regions.providers.AwsRegionProviderChain.getRegion(AwsRegionProviderChain.java:70) ~[regions-2.28.18.jar:na]
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveRegion(AwsDefaultClientBuilder.java:370) ~[aws-core-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:604) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:593) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:400) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$Builder.internalGet(AttributeMap.java:389) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$Builder.access$1300(AttributeMap.java:201) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$Builder$1.get(AttributeMap.java:403) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.services.s3.DefaultS3BaseClientBuilder.lambda$finalizeServiceConfiguration$2(DefaultS3BaseClientBuilder.java:197) ~[s3-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:604) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:593) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:400) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$Builder.internalComputeIfAbsent(AttributeMap.java:331) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.utils.AttributeMap$Builder.putLazyIfAbsent(AttributeMap.java:275) ~[utils-2.28.18.jar:na]
	at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.lazyOptionIfAbsent(SdkClientConfiguration.java:182) ~[sdk-core-2.28.18.jar:na]
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeAwsConfiguration(AwsDefaultClientBuilder.java:188) ~[aws-core-2.28.18.jar:na]
	at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:170) ~[aws-core-2.28.18.jar:na]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:237) ~[sdk-core-2.28.18.jar:na]
	at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:51) ~[s3-2.28.18.jar:na]
	at software.amazon.awssdk.services.s3.DefaultS3AsyncClientBuilder.buildClient(DefaultS3AsyncClientBuilder.java:27) ~[s3-2.28.18.jar:na]
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:173) ~[sdk-core-2.28.18.jar:na]
	at software.amazon.awssdk.services.s3.S3AsyncClient.create(S3AsyncClient.java:24264) ~[s3-2.28.18.jar:na]
	at software.amazon.nio.spi.s3.S3ClientProvider.generateClient(S3ClientProvider.java:102) ~[aws-java-nio-spi-for-s3-2.1.0.jar:na]
	at software.amazon.nio.spi.s3.S3FileSystem.client(S3FileSystem.java:416) ~[aws-java-nio-spi-for-s3-2.1.0.jar:na]
	at software.amazon.nio.spi.s3.S3FileSystemProvider.newFileChannel(S3FileSystemProvider.java:826) ~[aws-java-nio-spi-for-s3-2.1.0.jar:na]
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309) ~[na:na]
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369) ~[na:na]
```

**Comment by markjschreiber** [comment]
The library will determine your region based on the standard Java SDK v2 rules. https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html

So the region could be determined from (among other things):
1. `AWS_REGION` environment variable or `aws.region` system variable
2. `AWS_PROFILE` envronment variable or `aws.profile`
3. metadata endpoints on EC2 or ECR/ EKS containers
4. Hard coded variables in code.
5. Information in `~/.aws/config` or `~/.aws/credentials`

The exact list and order or precedence comes from `DefaultAwsRegionProviderChain`. 

When it comes to accessing S3 buckets, when the Filesystem is created the library will attempt to determine the location of the bucket and create a client for that bucket configured with the correct region. This is important because calls to buckets must be made by the clients from the appropriate regions otherwise the SIGV4 signature will not be accepted.

On the whole, you probably don't need to set the region in your code, rather you can just run with an `AWS_PROFILE` set or run in an EC2 with an instance profile (role).

**Comment by markjschreiber** [comment]
Having said that, the `newFileChannel` implementation is quite new so a bug is not impossible.

**Comment by blacelle** [comment]
> All it is doing is making an S3AsyncClient.create(). You could test a small app in your environment to see if you are able to create a client with this single call.

It works if I did not removed `System.clearProperty("aws.region");` in the meantime. I'm not considering a piece of software deployed in a specific region (not even some code necessarily deployed in AWS).

Why would I call `System.clearProperty("aws.region");`? As I understand I need to set `aws.region` to the bucket region. (Indeed, if I do not set an `aws.region`, `S3AsyncClient.create()` will fail.).

Maybe I should understand I can pick any region as:
- `S3AsyncClient.create()` do not need to see the bucket region in `aws.region`
- An `S3AsyncClient` is cross bucket. Would you confirm an `S3AsyncClient` is also cross-region? (Hence, `aws.region` is just informative as long as my runtime is out of AWS infrastructure ; it is not used relatively to the targetted buckets).
- In a given JVM, I can freely open `S3FileSystems` on different buckets, along different regions. I just need to provide some default `aws.region` for whatever reason.
- This may relates to https://github.com/awslabs/aws-java-nio-spi-for-s3/issues/353, my scenario (cross-region, runtime out of AWS) why some default region mechanisms used to exist.

**Comment by blacelle** [comment]
> when the Filesystem is created the library will attempt to determine the location of the bucket and create a client for that bucket configured with the correct region. 

Well, the stack (and the code with superficial eye) suggests an S3AsyncClient is created on a per-Path basis (e.g. on `.newFileChannel`), not at `S3FileSystem` creation.

> This is important because calls to buckets must be made by the clients from the appropriate regions otherwise the SIGV4 signature will not be accepted

This makes me feel I'm mostly wrong in my previous comment. Hence questioning: is there room for cross-region `S3FileSystem` in a single JVM?

**Comment by markjschreiber** [comment]
> It works if I did not removed `System.clearProperty("aws.region");` in the meantime. I'm not considering a piece of software deployed in a specific region (not even some code necessarily deployed in AWS).
> 

You do need to have a region specified somewhere either as an environment variable, as part of your AWS profile or in code. 

> Why would I call `System.clearProperty("aws.region");`? As I understand I need to set `aws.region` to the bucket region. (Indeed, if I do not set an `aws.region`, `S3AsyncClient.create()` will fail.). (So, my current underatanding is I should wap `aws.region` dynamically (on each `Path`) to manage a cross-region scenario).
> 

You may not know the region of a bucket, especially if it is a publicly available data repository. You would usually set your region to the region that your bucket is in but if you are working across buckets in two regions then you can't set two regions so you would select one (it doesn't matter which).

> Maybe I should understand I can pick any region as:
> 
> * `S3AsyncClient.create()` do not need to see the bucket region in `aws.region`

You don't have to set `aws.region` but you DO have to configure a region in one of standard AWS ways. A region is required. `S3AsyncClient.create()` will use whatever region is found by the `DefaultAwsRegionProviderChain`.

> * An `S3AsyncClient` is cross bucket. Would you confirm an `S3AsyncClient` is also cross-region? (Hence, `aws.region` is just informative as long as my runtime is out of AWS infrastructure ; it is not used relatively to the targetted buckets).

It is not cross region. In the library we cache one client per bucket and each client is configured with the region of the bucket.

> * In a given JVM, I can freely open `S3FileSystems` on different buckets, along different regions. I just need to provide some default `aws.region` for whatever reason.

Correct.

> * This may relates to [AWS_REGION is ignored => region is locked to us-east-1 #353](https://github.com/awslabs/aws-java-nio-spi-for-s3/issues/353), my scenario (cross-region, runtime out of AWS) why some default region mechanisms used to exist.

Partially

**Comment by markjschreiber** [comment]
> This makes me feel I'm mostly wrong in my previous comment. Hence questioning: is there room for cross-region `S3FileSystem` in a single JVM?

In this lib each bucket is it's own `FileSystem` therefore to work across two buckets, two FileSystems would be created.

**Comment by blacelle** [comment]
> You don't have to set aws.region but you DO have to configure a region in one of standard AWS ways. A region is required. S3AsyncClient.create() will use whatever region is found by the DefaultAwsRegionProviderChain.

This is very clear. I do rely on `Set.property('aws.region', 'someRegion')` as it is the simpler way in my case to setup DefaultAwsRegionProviderChain. Still, how can I manage buckets in different regions given a single DefaultAwsRegionProviderChain/JVM?

> In this lib each bucket is it's own FileSystem therefore to work across two buckets, two FileSystems would be created.

Yes. This is part of the initial question: `I need to use concurrently multiple S3FileSystem, for different buckets in different AWS regions`.

> It is not cross region. In the library we cache one client per bucket and each client is configured with the region of the bucket.

I insist. The stack I provided, and the code as I saw in this library suggest a `S3AsyncClient` is created on each `Path` being considered, hence not being  created with `S3FileSystem`, nor memoized/cache on first use .

I get what's going on:

`software.amazon.nio.spi.s3.S3ClientProvider.generateClient(String, S3AsyncClient)` relies on a `bucketClientCache`. Hence, `S3AsyncClient` seems memoized, but not created with `S3FileSystem`. Once memoized, we still create another `S3AsyncClient` on each path: 

```
[S3ClientProvider]

    protected S3AsyncClient generateClient(String bucket) {
        try {
            return generateClient(bucket, S3AsyncClient.create()); // <-- `generateClient` would rely on a cache, but we always create an additional `S3AsyncClient.create()` for location detection.
        } catch (ExecutionException e) {
            throw new RuntimeException(e);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
            throw new RuntimeException(e);
        }
    }
```

The `locationClient` is documented with `recommend using {@code S3ClientProvider#UNIVERSAL_CLIENT}`. Why do we generate a fresh `S3AsyncClient` then? Quick-read through `getBucketLocation` suggests we rely on `universalClient` only if `.headBucket` failed. Looking at this class, I see: we infer the region only if `configuration.endpointUri() == null`, as we may get the region from `configuration.getRegion()`.

Hence, I understand:
- I hoped I could specify implicitly a region in a `S3FileSystem` through the URI of `public FileSystem newFileSystem(final URI uri, final Map<String, ?> env)`, but `S3FileSystemInfo.endpoint` seems not tweakable . Hence `.withEndpoint(info.endpoint())` is a no-op in `S3FileSystemProvider.getFileSystem`.
- Even if this was a way forward, there would still be unexpected `S3AsyncClient` generated unecessarily in `software.amazon.nio.spi.s3.S3ClientProvider.generateClient(String)` (by unnecessary, I mean we create a `S3AsyncClient` while it may not be used at all (e.g. if the bucket S3Client is in cache and not closed, or even simpler if the bucket-region is in cache)).
- Is there a way to create a `S3FileSystem` given my own `S3NioSpiConfiguration`?
- I feel I need to setup `aws.region` only for the `regionDetector` `S3Client`, even though I *feel* the `universalClient` could do the job.

**Comment by blacelle** [comment]
All-in-all:
- One need to have an `aws.region` defined at all time, due to spurious `S3AsyncClient` creations
- However, this region is not a strong constraint regarding used buckets: the library takes care of inferring the actual bucket region, using the `DefaultAwsRegionProviderChain` region as the region of the `locationClient`/bucketRegionDetector.

**Comment by markjschreiber** [comment]
One reason why we create a client and then potentially fall back on the "universal" client to determine location is because the HeadBucket call must be made with a client in the bucket region whereas any call to GetBucketLocation must be done in us-east-1. GetBucketLocation is deprecated now so we may change the logic. 

The approach is convoluted because s3 paths say nothing about region and we can't guarantee that any individual user will have permissions for HeadBucket or GetBucketLocation so we try several approaches. 

To make things more efficient, we could add options to configure the library so that it will only attempt connections in one region, or we could have a configuration option to provide a list of region names with bucket names so the library can avoid making the location lookup.

**Comment by blacelle** [comment]
> One reason why we create a client and then potentially fall back on the "universal" client to determine location is because the HeadBucket call must be made with a client in the bucket region whereas any call to GetBucketLocation must be done in us-east-1. GetBucketLocation is deprecated now so we may change the logic.

Supposing `GetBucketLocation` would be dropped, given `HeadBucket` needs to be done with the proper region, it would be nice to be able to provide the region explicitly, especially in cross-region scenario (like mine). Hence, I understand that in my case, the buckets within the `DefaultAwsRegionProviderChain` get there region confirmed by `HeadBucket` ; while the other (cross-region) buckets do rely on `GetBucketLocation ` (which is deprecated).

The region could also be computed once and for all (to prevent creating `S3AsyncClient`). This information is currently cached for 15 minutes ; I suppose it is especially relevant for (edge-)case where a bucket is deleted and re-created in a different region (I believe a bucket can not be migrated).

Could the region  be expressed in the URI, like something like `s3://<region>:<bucket_name>` ? Or rather something following the [API endpoint](https://docs.aws.amazon.com/general/latest/gr/s3.html): `s3.eu-south-1.amazonaws.com`? (As a library-user, I feel comfortable providing myself each bucket region, than relying on automated detection).

Also, as you enabled crossRegion (https://github.com/awslabs/aws-java-nio-spi-for-s3/issues/206), a naive question is: `Why not just letting the AsyncClient pick its region?`:

```
    /**
     * Configure the region with which the SDK should communicate.
     *
     * <p>If this is not specified, the SDK will attempt to identify the endpoint automatically using the following logic:
     * <ol>
     *     <li>Check the 'aws.region' system property for the region.</li>
     *     <li>Check the 'AWS_REGION' environment variable for the region.</li>
     *     <li>Check the {user.home}/.aws/credentials and {user.home}/.aws/config files for the region.</li>
     *     <li>If running in EC2, check the EC2 metadata service for the region.</li>
     * </ol>
     *
     * @param region the region to be used
     * @return this builder for method chaining.
     */
    S3CrtAsyncClientBuilder region(Region region);
```

**Comment by markjschreiber** [comment]
> Why not just letting the AsyncClient pick its region?
Unfortunately you can't change the region of a client once it is created. If you could then I agree things would be easier.

> Could the region be expressed in the URI, like something like s3://<region>:<bucket_name> ? Or rather something following the [API endpoint](https://docs.aws.amazon.com/general/latest/gr/s3.html): s3.eu-south-1.amazonaws.com? (As a library-user, I feel comfortable providing myself each bucket region, than relying on automated detection).

This is mainly because this library is intended to operate as a NIO SPI meaning you can include it on the classpath of any Java application that is reading files using NIO Paths and anytime the application sees an `s3` URI then it will automatically switch to using this library as the provider. No changes or recompilation are needed in the original application (it can now read local and S3 files).  So the design idea is that it should "just work" with little (or preferably) no configuration. A URI like `s3://<region>:<bucket_name>` is not a recognized S3 URI that you can use with any other S3 tool. It also isn't any URI that you can get from any S3 service so I don't know if we can expect people to use this form.

Even S3 bucket ARNs don't have regions so we couldn't use that information either. 

A lot of this is due to the legacy of S3 predating AWS regions and even AWS accounts (which is why S3 bucket names must be globally unique and not just unique in the context of an account/ region).

**Comment by blacelle** [comment]
> Unfortunately you can't change the region of a client once it is created. If you could then I agree things would be easier.

Why changing the client region? The documentation states that if the client is cross-region, then a first query with wrong region (given DefaultAwsRegionProviderChain ) would return an error, and the region will turn automatically with the adequate region.

> If the bucket does not exist in that specific Region, the error response includes the actual Region where the bucket resides. The SDK then uses the correct Region in a second request.

> To optimize future requests to the same bucket, the SDK caches this Region mapping in the client.

It even suggests a single cross-region asyncClient could manage different buckets in different regions. This seems confirmed by [S3CrossRegionAsyncClient](https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/crossregion/S3CrossRegionAsyncClient.java) (regarding both caching an redirection).

**Comment by markjschreiber** [comment]
Interesting. This seems like new behavior than what the client previously did. It also means it behaves more like Boto3. I will try to find some time to investigate this as it would make things simpler.
