### ISSUE TITLE
Enabling logging for the Aws Client

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#65]
Hey,
It's probably a dumb question, but how can I enable logging for the underlying aws client?

**Comment by stefanofornari** [comment]
BTW, this is only half dumb question ... using the S3SDK directly I manage to control what to log, using aws-java-nio no.

**Comment by markjschreiber** [comment]
The AWS Java SDK uses slf4j logging which is also the same logging that we use so you can enable it by running with the appropriate logging configuration file. There are a few examples here. For development you might want to enable the more verbose options. https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html
