### ISSUE TITLE
Unneeded new file system instance in newDirectoryStream

### ISSUE THREAD

**Issue by stefanofornari** [awslabs/aws-java-nio-spi-for-s3#96]
https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/ea1044d51bb4f61af05b6651539a719b7a03c529/src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java#L263

I suspect this is incorrect because it creates a new file system instead of using the s3Pth.getFileSystem()

**Comment by markjschreiber** [comment]
Good spotting.

**Comment by markjschreiber** [comment]
Can you take a look at PR #102? It fixes this issue and in my testing on a large and deeply nested bucket using [src/main/java/examples/WalkFromRoot.java](https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/102/files#diff-6f994feb90338d6be064cfd2b7ad4aca0d32a18f7e7eea4a409ce83f5f8b3363) it seems to give the expected results.

I need to add a few more unit tests but do let me know if this works for you

**Comment by markjschreiber** [comment]
Fixed and merged into main

**Comment by stefanofornari** [comment]
looks good and working for me.
